 @startuml
component "MicroBit Main-MCU" as MBMCU {
[Software]
}
[MicroBit Debug-CPU] as MBUSB
component PC {
  component OpenOCD
  component GDB
}
PlatformIO -> GDB
GDB -> OpenOCD
OpenOCD -> MBUSB
MBUSB -> Software
@enduml
