 @startuml
component "BBC Micro:Bit" {
"Main-MCU" as MBMCU {
[Software]
}
[Debug-CPU] as MBUSB
}

component PC {
  component OpenOCD
  component GDB
}
PlatformIO -> GDB
GDB -> OpenOCD
OpenOCD -> MBUSB
MBUSB -> Software
@enduml
